# -----------------------------------------------------------
# Name       : Rajarshi Sen
# Z_Id       : z1816768
# Course     : CSCI 689
# Section    : 1
# Due Date   : January 27, 2017 by midnight
# Description: to help create the executable of Assignment-1
#              and clear out the project to pristine state.
# -----------------------------------------------------------
assign1:assign1.o
	g++ -o assign1 assign1.o
assign1.o:assign1.cc
	g++ -c -Wall assign1.cc -lm
clean:
	rm *.o assign1


